name: Notify pkg.go.dev

on:
  push:
    tags: [v*]

jobs:
  notify:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Trigger pkg.go.dev update
        run: |
          MOD=$(grep '^module ' go.mod | awk '{print $2}')
          VERSION="${GITHUB_REF#refs/tags/}"
          URL="https://pkg.go.dev/fetch/${MOD}@${VERSION}"
          curl --fail-with-body --max-time 10 --retry 5 --retry-connrefused -X POST "$URL"
